name: build_and_push

on:
  push:
    branches:
      - main
      - develop

env:
  AWS_REGION: ap-northeast-1

jobs:
  build:
    name: Build And Push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for prod
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 1800

      - name: Configure AWS credentials for dev
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 1800
  
